# Custom Language File for Launcher Customizer

[ejs.app]
title = "Kindly Klan Launcher"

[ejs.landing]
mediaGitHubURL = "https://kindlyklan.com"
mediaXURL = "https://x.com/KindlyKlan"
mediaInstagramURL = "https://www.instagram.com/kindlyklan"
mediaYouTubeURL = "https://www.youtube.com/channel/UCbVZrvJcHUL6nxqmBCzUvkw"
mediaDiscordURL = "https://discord.gg/kindlyklan"

[ejs.settings]
sourceGithubLink = "https://github.com/javivi09dev/KindlyKlanLauncher"
supportLink = "https://github.com/javivi09dev/KindlyKlanLauncher/issues"

[ejs.welcome]
welcomeHeader = "¡Gracias por descargar el Launcher!"
welcomeDescription = "Somos Kindly Klan. Encargados de crear eventos por y para la comunidad."
welcomeDescCTA = "Empezar"
