# Custom Language File for Launcher Customizer

[ejs.app]
title = "Kindly Klan Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "¡Gracias por descargar el Launcher!"
welcomeDescription = "Somos Kindly Klan. Encargados de crear eventos por y para la comunidad."
welcomeDescCTA = "Empezar"
